version:  '3.5'
services:
    php:
        build:
            context: .
            dockerfile: php/Dockerfile          
        volumes:
            - '../:/usr/src/app'
        restart: on-failure
        user: 1000:1000
